[package]
name = "calorie_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
fuzzy-matcher = "0.3.7"
serde_json = "1.0"
